### ISSUE TITLE
Inconsistent message handling by ZMQ core broker

### ISSUE THREAD

**Issue by gayukrishna** [GMLC-TDC/HELICS-src#527] opened 2018-12-07 20:53 UTC
The Bug:
When doing scalability testing on ZMQ core with python API, the broker gives a "core tick" and "unable to terminate transmit connection" when running more than few federates and more than few publications/subscriptions.

The tests done involved many to one echo process i.e., a fixed number of federates (senders) sending a fixed number of messages to one echoer and the echoer sending back the corresponding messages it received from each federate (sender).

Test- example, and result:
Three different cases where 1000 publications and subscriptions were involved is explained below:
1.  10 federates (sender) each sending 100 messages to one echoer and subscribing them back - Echoer gave a consistent "core tick" log and did not complete the process.
2. 100 federates (sender) each sending 10 messages to one echoer and subscribing them back  - Echoer gave an "unable to terminate transmit connection" log and did not complete the process.
3. 1000 federates each sending 1 message to the echoer and subscribing them back - completes the process cleanly but is inconsistent.

All three cases involved publishing/subscribing to the same number of messages but exhibit different outcomes.

Codes to reproduce the behavior: Python_fedgenerator.zip
Steps to reproduce the behavior: readme.txt in the zip folder

[Python_fedgenerator.zip](https://github.com/GMLC-TDC/HELICS-src/files/2659048/Python_fedgenerator.zip)

**Environment (please complete the following information):**
 - Operating System: [Linux]
 - Language Extension: Python 
 - HELICS version: --> 2.0.0 beta.1

**Comment by Jacobhansens** [comment] 2018-12-07 21:30
I see that you are using the HELICS Runner. As far as I can see this piece of software has not been updated for 2.0 yet. Let me explain. For the 2.0 version of HELICS the broker needs to be executed differently than with 1.3. Specifically you need to do the following:

`helics_broker --federates=<number of feds>`

Looking at the source for the HELICS Runner this change is not made. Did you make this change locally?

**Comment by gayukrishna** [comment] 2018-12-07 23:17
I am using HELICS Runner to run the simulation, but not to create the broker. 

I have the broker creation inside the echoer.py script where I create the broker using this coreinitstring:
coreinitstring = ("--federates=%s --name=mainbroker" %(number_sender+1)). 

Also, the script is changed to adapt to new HELICS 2.0 functions.

**Comment by Jacobhansens** [comment] 2018-12-09 20:55
I see, I should have looked more carefully!

I am able to reproduce your problem consistently on my end as well. I discussed with Mark and we were not able to immediately find a permanent fix for this. What causes the problem in this case seems to be two-fold. First problem is that the sender.py and echoer.py are not exiting at the same granted time (sender.py is not calling time request for the stop time while the echoer.py is). Second one is the fact that once each federate gets granted their last time to run they have different amount of code to run because the time request is in the beginning of the while loop. In a perfect world none of these factors should stall the simulation and have it not exit cleanly. I think we definitely need to get to the bottom of why this is happening.

In the mean time however, I do have a temporary fix you can use if you need to collect results now. For the temporary fix change the following:

**sender.py:**
Change line 54 from `t = update_interval` to `t = 0`
Move line 76 ` t = t + update_interval` to line 55 (beginning of while loop)
After line 58 `print("Granted Time = {}".format(currenttime))` add the following two lines:
```
if currenttime >= time_stop:
        continue 
```

**echoer.py:**
After line 74 `print("Granted Time = {}".format(currenttime))` add the following two lines:
```
if currenttime >= time_stop:
        continue 
```

While tinkering with the code I did find two things I wanted to bring up:

- From the description you mention that the echoer is suppose to just reply back what it receives. While it does do that it is not only sending the message back to where it came from but rather what happens is that you loop over each subscription and then publishes the received value on all the publication of the echoer. That means for a case with 10 federates, each with 100 messages the echoer is publishing 1,000,000 times rather than the 1,000 required to to echo the received values. Is that what you intended to do for this case? 

- Also, I noticed that you only set the timeDelta in the JSON config. Nothing wrong with doing this but that means that your base time will be nano seconds. I find that hard to read myself so while testing I added the period to be 1 seconds as well as that will force the time base to be 1 second. This helped me identify the temporary fix as well

**Comment by Jacobhansens** [comment] 2018-12-13 22:16
I tested this with the changes from #531 and now the simulation exits as expected. A lot of warnings are thrown from broker that messages are being dropped but that is due to how the federates are designed

**Comment by Jacobhansens** [comment] 2018-12-13 22:44
That is a good question. I will say that the first time I saw it I immediately thought something was wrong. I had to really pay attention and see what was causing it and then it made sense. I definitely think we should do something. Would it be possible to add a check to see if the federate disconnected. Then in the case where the federate is disconnected not log the message at warning level but rather summery level. I think the message is valid but as you mention I think many people will run into this and think something is wrong. I am open to suggestions as well and maybe we want to discuss with more people that might have input.

**Comment by phlptp** [comment] 2018-12-13 23:12
There is already a check before a message gets generated.  You see those warnings from messages that get sent in time between the check and the actual network transmission which could have disconnected.  And the network stuff doesn't know much about the disconnection.  It doesn't show the message if it is related to disconnection, otherwise you would see a bunch more.    Also the networking layer is not fully aware of the warning levels since that occurs pretty low down on the stack.    I will look into it further.

**Comment by Jacobhansens** [comment] 2018-12-13 23:19
Thank you for the additional information. I will keep thinking about it as well. I am also pretty sure that one could avoid these messages with small changes to the federate design. I will try that on my end actually

**Comment by Jacobhansens** [comment] 2018-12-14 18:05
I have been able to avoid the dropped message warning by ensuring that no federates are publishing on their last time step. This only works of course if all federates end at the same time but I think all the co-simulation I have worked on is intended to run this way.

**Comment by Jacobhansens** [comment] 2018-12-14 18:05
I think this issue can be closed as the problem is no longer present after #531

**Closed** 2018-12-14 18:53 UTC
Labels: bug, performance/scalability
